version: '3'
services:
  fevg:
    image: fareasternvikings/fevg-admin:0.0.1
    restart: always
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: fevgDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    deploy:
      replicas: 1
    ports:
      - '1337:1337'
    depends_on:
      - fevgDB

  fevgDB:
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: always
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - fevg-data:/var/lib/postgresql/data/ #using a volume

    ports:
      - '5432:5432'

volumes:
  fevg-data:
